---

- hosts: unix
  environment:
    PATH: /usr/local/opt/python@2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin

  tasks:
  - name: Running git-autopull
    include_role:
      name: git-autopull
    environment:
      PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
    tags: autopull

  - name: Running install-apt
    include_role:
      name: install-apt
    when: ansible_os_family == "Debian"
    become: true
    tags: apt

  - name: Running apt-updates
    include_role:
      name: apt-updates
    when: ansible_os_family == "Debian"
    become: true
    tags: apt

  - name: Running pip-upgrade
    include_role:
      name: pip-upgrade
    become: true
    tags: pip

  - name: Sync Standard Config Files
    include_role:
      name: sync-config
    become: true
    tags: config

  - name: Running brew-updates
    include_role:
      name: brew-updates
    when: ansible_os_family == "Darwin"
    environment:
      PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin"
    tags: brew
