---

- hosts: all

  tasks:
  - name: Running jpartain89.git
    import_role:
      name: jpartain89.git
    tags: git
    failed_when: false

  - name: Running apt-updates
    import_role:
      name: install-apt
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - updates
    failed_when: false

  - name: Running brew-updates
    import_role:
      name: brew-updates
    tags:
      - brew
      - updates
    failed_when: false
    #when: ansible_os_family == "Darwin"

  - name: git-autopull
    import_role:
      name: git-autopull
    tags:
      - git
      - autopull
    failed_when: false
