---

- hosts: all

  tasks:
  - name: Running jpartain89.git
    import_role:
      name: ansible-role-git
    tags: git
    failed_when: false

  - name: Running apt-updates
    import_playbook:
      name: apt_update.yml
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - updates
    failed_when: false

  - name: Sync Standard Config Files
    import_role:
      name: sync-config
    tags: config
    failed_when: false

  - name: Running brew-updates
    import_role:
      name: brew-updates
    when: ansible_os_family == "Darwin"
    tags:
      - brew
      - updates
    failed_when: false
