---

- hosts: all

  tasks:
  - name: Running jpartain89.git
    include_role:
      name: jpartain89.git
    tags: git

  - name: Running git-autopull
    include_role:
      name: git-autopull
    tags:
      - autopull
      - git

  - name: Running apt-updates
    include_role:
      name: apt-updates
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - updates

  - name: Sync Standard Config Files
    include_role:
      name: sync-config
    tags: config

  - name: Running brew-updates
    include_role:
      name: brew-updates
    when: ansible_os_family == "Darwin"
    tags:
      - brew
      - updates
