---

- hosts: all
  environment:
    PATH: /usr/local/opt/python@2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin

  tasks:
  - name: Running jpartain89.git
    include_role:
      name: ../ansible-role-git
    tags: git

  - name: Running git-autopull
    include_role:
      name: git-autopull
    tags:
      - autopull
      - git

  - name: Running install-apt
    include_role:
      name: install-apt
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - updates

  - name: Running apt-updates
    include_role:
      name: apt-updates
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - updates

  - name: Running pip-upgrade
    include_role:
      name: pip-upgrade
    tags:
      - pip
      - updates

  - name: Sync Standard Config Files
    include_role:
      name: sync-config
    tags: config

  - name: Running brew-updates
    include_role:
      name: brew-updates
    when: ansible_os_family == "Darwin"
    tags:
      - brew
      - updates
