---

collections:
  - name: middleware_automation.keycloak

roles:
  - src: jpartain89.ddclient
  - src: jpartain89.git
  - src: geerlingguy.dotfiles
  - src: git@github.com:jpartain89/ansible-role-monit-from-source
    name: jpartain89.install-monit-from-source
    scm: git
  - src: jpartain89.install-nginx
  - src: jpartain89.logrotate
  - src: jpartain89.install-monit-binary
  - src: git@github.com:jpartain89/ansible-role-configure-monit
    name: jpartain89.configure-monit
    scm: git
