---

- hosts: all

  tasks:
  - name: Running git-autopull
    import_role:
      name: git-autopull
    environment:
      PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
    tags: autopull

  - name: Running apt-updates
    import_role:
      name: apt-updates
    when: ansible_os_family == "Debian"
    become: true
    tags: apt

  - name: Running brew-updates
    import_role:
      name: brew-updates
    when: ansible_os_family == "Darwin"
    environment:
      PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin"
    tags: brew

  - name: Running pip-upgrade
    import_role:
      name: pip-upgrade
    become: true
    tags: pip

  - name: Sync Standard Config Files
    import_role:
      name: sync-config
    become: true
    tags: config
