---
# install-apt/tasks/main.yml
# This is to install apps I use on all platforms, and run through all upgrades.

- name: Template out sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: yes
    mode: 0644
    owner: root
    group: root
  register: template_sources_list
  notify: Update Apt Cache
  become: true
  when:
    - apt_sources is defined

- name: Force Update Apt Cache - if needed
  meta: flush_handlers
  become: true

- name: Install apt-get Universal Requirements
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time_var }}"
  with_items: "{{ apt_standard_install }}"
  become: true

- name: sudo apt-get upgrade
  apt:
    upgrade: full
  register: upgrade_apt
  become: true

#- debug: var=upgrade_apt

- name: sudo apt-get dist-upgrade
  apt:
    upgrade: dist
  register: dist_apt
  become: true

#- debug: var=dist_apt

- name: apt-get autoclean
  apt:
    autoclean: yes
  register: autoclean_apt
  become: true
  failed_when: false

#- debug: var=autoclean_apt

- name: AutoRemove Apt Packages
  apt:
    autoremove: yes
    purge: yes
  register: ara
  become: true

#- debug: var=ara

- name: Autoremove "rc" labeled apps
  shell:
    'apt-get autoremove --purge -y $(dpkg --list | grep `^rc` | awk `{print $2}`)'
  register: autoremove_rc_apt
  become: true

#- debug: var=autoremove_rc_apt
