---
# defaults file for install-nginx

nginx_url: "http://nginx.org/download/{{ nginx_version }}.tar.gz"
pcre_url: "https://ftp.pcre.org/pub/pcre/{{ pcre_version }}.tar.gz"
zlib_url: "http://zlib.net/{{ zlib_version }}.tar.gz"
openssl_url: "http://www.openssl.org/source/{{ openssl_version }}.tar.gz"

nginx_script:
  prefix: /usr/share/nginx
  sbin_path: /usr/sbin/nginx
  conf_path: /etc/nginx/nginx.conf
  http_log_path: /var/log/nginx/access.log
  error_log_path: /var/log/nginx/error.log
  lock_path: /var/lock/nginx.lock
  pid_path: /run/nginx.pid
  modules_path: /usr/lib/nginx/modules
  http_client_body_temp_path: /var/lib/nginx/body
  http_fastcgi_temp_path: /var/lib/nginx/fastcgi
  http_proxy_temp_path: /var/lib/nginx/proxy
  http_scgi_temp_path: /var/lib/nginx/scgi
  http_uwsgi_temp_path: /var/lib/nginx/uwsgi
  with:
    - 'debug'
    - 'pcre-jit'
    - 'http_ssl_module'
    - 'http_stub_status_module'
    - 'http_realip_module'
    - 'http_auth_request_module'
    - 'http_dav_module'
    - 'http_slice_module'
    - 'threads'
    - 'http_addition_module'
    - 'http_geoip_module=dynamic'
    - 'http_gunzip_module'
    - 'http_gzip_static_module'
    - 'http_sub_module'
    - 'http_xslt_module=dynamic'
    - 'stream=dynamic'
    - 'stream_ssl_module'
    - 'mail=dynamic'
    - 'mail_ssl_module'

nginx_module:
  - { name: "ngx_http_auth_pam_module", address: "https://github.com/sto/ngx_http_auth_pam_module.git"}

nginx_prerequisites:
  - build-essential
  - git
  - gcc
  - make
  - libpcre3-dev
  - libssl-dev
  - checkinstall
  - auto-apt
