---

main_mac_path:
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/bin
  - /usr/sbin
  - /bin
  - /sbin

mac_path:
  - name: Cellar
    location: /usr/local/Cellar
  - name: MacGPG2
    location: /usr/local/MacGPG2/bin
  - name: XQuartz
    location: /opt/X11/bin
