---

- name: Clone git-autopull's Repo
  git:
    repo: "{{ git_address.github_ssh }}:jpartain89/git-autopull.git"
    dest: "{{ git_dir.path }}/git-autopull"
    recursive: yes

- name: Install/Run git-autopull
  command: "./git-autopull"
  args:
    chdir: "{{ git_dir.path }}/git-autopull"
  failed_when: false

- name: Stat that the Entry Git Repo is Cloned
  stat:
    path: "{{ git_dir.path }}/dotfiles"
  register: _git_repo_dotfiles_stat
  failed_when: False

#- debug: var=_git_repo_dotfiles_stat

- name: Clone the Dotfiles Repo if its Missing
  git:
    repo:  "{{ git_address.gitlab_ssh }}jpartain89/dotfiles.git"
    dest: "{{ git_dir.path }}/dotfiles"
    update: yes
  failed_when: False
  when: _git_repo_dotfiles_stat.stat.exists == "false"


#- debug: var=_git_autopull_debug
