---

- name: Checking (and if not, overwriting) The BrewFile
  lineinfile:
    dest: ~/.config/brewfile/Brewfile
    line: "{{ brewfile_git_repo }}"
    backup: yes
  register: _brewfile_git_update

- name: Running Brew Update
  homebrew:
    update_homebrew: yes
  failed_when: False

- name: Running Brew Upgrade
  homebrew:
    upgrade_all: yes
  failed_when: False

- name: Running Brew Cleanup
  shell: /usr/local/bin/brew cleanup
  args:
    executable: /usr/local/bin/bash
  failed_when: false

- name: Running Brew Doctor
  shell: /usr/local/bin/brew doctor
  args:
    executable: /usr/local/bin/bash
  failed_when: false

- name: Running Brew Cask Doctor
  shell: /usr/local/bin/brew cask doctor
  args:
    executable: /usr/local/bin/bash
  failed_when: false

- name: Running softwareupdate Command
  shell: 'softwareupdate -ia'
  args:
    executable: /usr/local/bin/bash
  register: _softwareupdate
  failed_when: False
