---

- name: Running brewdate
  shell: 'brewdate'
  args:
    executable: /usr/local/bin/bash
  register: _brewdate
  failed_when: False

- debug: var=_brewdate

- name: Running softwareupdate Command
  shell: 'softwareupdate -ia'
  args:
    executable: /usr/local/bin/bash
  register: _softwareupdate
  failed_when: False

- debug: var=_softwareupdate
