---

- name: Install New Apps (and save them into the BrewFile)
  homebrew:
    state: latest
    name: "{{ item }}"
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - "{{ new_homebrew.apps }}"

- name: Install New Cask Apps
  homebrew_cask:
    state: present
    name: "{{ item }}"
    update_homebrew: yes
  with_items:
    - "{{ new_homebrew.cask }}"

- name: Checking (and if not, overwriting) The BrewFile
  lineinfile:
    dest: ~/.config/brewfile/Brewfile
    line: "{{ brewfile_git_repo }}"
    backup: yes
  register: _brewfile_git_update

- debug: var=_brewfile_git_update

- name: Running BrewFile Update with Clean
  shell: '/usr/local/bin/brew-file update -C'
  register: _brewfile_update

- debug: var=_brewfile_update

- name: Running brewdate
  shell: 'brewdate'
  args:
    executable: /usr/local/bin/bash
  register: _brewdate
  failed_when: False

- debug: var=_brewdate

- name: Running softwareupdate Command
  shell: 'softwareupdate -ia'
  args:
    executable: /usr/local/bin/bash
  register: _softwareupdate
  failed_when: False

- debug: var=_softwareupdate
