---

- name: Install Universally Used pip Apps
  pip:
    name: "{{ universal_pip }}"
    state: latest
  failed_when: false

- name: Run my pip-upgrade Script
  script: pip-upgrade
  register: _pip_upgrade
  become: true
