---

- name: Install Universally Used pip Apps
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ universal_pip }}"
  failed_when: false

- name: Run my pip-upgrade Script
  script: pip-upgrade
  register: _pip_upgrade
  become: true
