---

- name: Run rpi-update
  command: '/usr/bin/rpi-update'
  register: _rpi_update

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: _rpi_update is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: _rpi_update is changed
