---

- name: Sync SSH Home Config
  template:
    src: ssh_home_config.j2
    dest: "{{ ansible_user_id }}/.ssh/config"
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    mode: 0644
    backup: yes
  register: _ssh_config
  failed_when: false
  become_user: "{{ become_user }}"

- name: Sync Low Level SSH Configs
  template:
    src: "etc_{{ item }}_config.j2"
    dest: "/etc/ssh/{{ item }}_config"
    backup: yes
  with_items:
    - ssh
    - sshd
  register: _etc_ssh_config
  when: ansible_os_family == "Debian"
  failed_when: false
#
#- name: Create Master Paths File
#  template:
#    src: mac_main_path.j2
#    dest: /etc/paths
#  register: _main_paths
#  when: ansible_os_family == "Darwin"
#  failed_when: false
#  become: true

- name: Create Paths Files
  template:
    src: mac_paths.j2
    dest: "/etc/paths.d/{{ item.name }}"
  register: _paths_files
  when: ansible_os_family == "Darwin"
  with_items: "{{ mac_path }}"
  failed_when: false
