---

- include_vars: main.yml

- name: Sync SSH Home Config
  template:
    src: ssh_home_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
    backup: yes
  register: _ssh_config

- debug: vars=_ssh_config
