---

ssh_config:
  proxyjumpers:
    rpi35:
      hostname: rpi35.jpcdi.com
      port: 22235
    'mark-server':
      hostname: mdusa.jpcdi.com
  servers:
    imac:
      hostname: imac.jpcdi.com
      proxyjump: rpi35
    macbook:
      hostname: macbook.jpcdi.com
    'mark-imac':
      hostname: 192.168.0.34
      proxyjump: mark-server
  defaults:
    '*':
      user: jpartain89
      forwardagent: yes
      controlmaster: Auto
      controlpath: "~/.ssh/mux-%r@%h:%p"
      controlpersist: 15m
