galaxy_info:
  author: Justin Partain
  description: Install Monit via their Git Repo
  company: JPCDI

  license: license (GPLv3)

  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  - name: Debian
    versions:
    - stretch
    - wheezy
  - name: MacOSX
    versions:
    - '10.12'
    - '10.13'

  galaxy_tags:
    - system
    - monitoring

dependencies: []
