---
# Task list for openssl

- name: Download openssl
  unarchive:
    src: "{{ openssl_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create auto-apt_openssl Script from Template | OpenSSL
  template:
    src: auto-apt_openssl.j2
    dest: "/tmp/nginx/auto-apt_openssl.sh"
    mode: 0775
  register: _auto_apt_openssl
  delegate_to: localhost

- debug: var='_auto_apt_openssl'

- name: Run Created Shell Script | OpenSSL
  script: /tmp/nginx/auto-apt_openssl.sh
  register: _auto_apt_openssl_sh
  notify: Delete OpenSSL Script

- debug: var=_auto_apt_openssl_sh
