---
# Task list for ZLIB

- name: Download ZLIB | ZLIB
  unarchive:
    src: "{{ zlib_url }}"
    dest: "/tmp/nginx"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: Create auto-apt_zlib Script from Template | ZLIB
  template:
    src: auto-apt_zlib.j2
    dest: "/tmp/nginx/auto-apt_zlib.sh"
    mode: 0775
  register: _auto_apt_zlib
  delegate_to: localhost

- debug: var='_auto_apt_zlib'

- name: Run Created Shell Script | ZLIB
  script: "/tmp/nginx/auto-apt_zlib.sh"
  register: _auto_apt_zlib_sh
  notify: Delete OpenSSL Script

- debug: var=_auto_apt_zlib_sh
