---

- name: Create Includes and Lib Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
  with_items:
    - "{{ monit_lib_folder }}"
    - "{{ monit_includes }}"
    - "{{ monit_log_dir }}"
    - "{{ monit_alert_defaults }}"

- name: Config | Setup monitrc
  template:
    src: monitrc.j2
    dest: "{{ monitrc_conf }}"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0700
  notify: restart monit

- name: Config | Setup Webinterface
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0660
  notify: restart monit

- name: Config | Setup Mail Alerts
  template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0660
  notify: restart monit
  when: monit_mail_enabled

- name: Config | Copy Over Alert Defaults
  copy:
    src: files/{{ item }}
    dest: "{{ monit_alert_defaults }}/{{ item }}"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0660
  with_items:
    - '3_5_cycles'
    - '5_7_7_10_cycles'
  notify: restart monit
