---

- name: Register Monit's Executable Location
  shell: 'command -v monit'
  register: _monit_executable
  failed_when: false

- set_fact:
  monit_executable: "{{ _monit_executable.stdout | default('/usr/local/bin/monit') }}"

- debug: var=monit_executable

- include_vars: debian.yml
  when:  ansible_os_family == "Debian"

- include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- include_vars: macOS.yml
  when: ansible_os_family == "Darwin"

- import_tasks: autostart.yml
  tags: monit_autostart
  become: true

- import_tasks: config.yml
  tags: monit_config
  become: true

- import_tasks: monitors.yml
  tags: monit_monitors
  become: true
