---

- name: Web | Setup Web Interface
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0660
  notify: restart monit
