---

- name: Debian | Install Required Apps
  apt:
    update_cache: yes
    cache_valid_time: 32400
    name: "{{ item }}"
    state: latest
  with_items:
    - html2text
    - wget
    - tar
  become: true
  when: ansible_os_family == "Debian"

- name: macOS | Install Required Apps
  homebrew:
    state: present
    name: "{{ item }}"
    update_homebrew: yes
  with_items:
    - html2text
    - wget
    - tar
  when: ansible_os_family == "Darwin"

- name: Register Monit's Published Version Number
  shell: "wget -q  {{ monit_binary_html }} -O - | html2text | grep DIR | tail -n 1 | tr -d / | awk '{print $2}'"
  register: _monit_binary_version

- debug: var=_monit_binary_version

- name: Download and Decompress Monit's Binary Files
  unarchive:
    src: "{{ monit_binary_html }}{{ _monit_binary_version.stdout }}/monit-{{ _monit_binary_version.stdout }}-{{ monit_os_var }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/monit-{{ _monit_binary_version.stdout }}"
  register: _monit_binary_downloaded

- debug: var=_monit_binary_downloaded

- name: Install New Monit Binary
  copy:
    dest: "{{ monit_executable }}"
    src: "/tmp/monit-{{ _monit_binary_version.stdout }}/bin/monit"
    remote_src: yes
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0555
  when: _monit_binary_downloaded|changed
  become: true
  notify:
    - 'Debian | Restart Monit'
    - 'macOS | Restart Monit'
