---

- include_vars: macOS.yml
  when: ansible_os_family == 'Darwin'
  failed_when: false

- include_vars: raspberry_pi.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_machine == 'armv7l'
  failed_when: false

- include_vars: debian_64.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_machine == 'x86_64'
  failed_when: false

- include_tasks: install_binary.yml
- include_tasks: monit_autostart.yml

- name: Remove Download Directory
  file:
    path: "/tmp/monit-{{ _monit_binary_version.stdout }}"
    state: absent
