---

- name: Template out sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: yes
    mode: 0644
    owner: root
    group: root
  register: template_sources_list
  become: true
  when:
    - apt_sources is defined
  failed_when: false

- name: Install 3 Base Apt-Utils and Update Cache
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  loop:
    - aptitude
    - apt
    - apt-utils
  become: true
  failed_when: false

- name: Run Basic, Safe, Full and Dist Upgrade with apt Module
  apt: upgrade="{{ item }}"
  loop:
    - "yes"
    - "safe"
    - "full"
    - "dist"
  register: _upgrade_apt
  failed_when: False
  become: True

- name: Autoremove Command in apt Module
  apt: autoremove=yes
  register: _autoclean_apt
  failed_when: False
  become: True

#- name: Check if Reboot is Needed
#  stat:
#    path: /var/run/reboot-required
#  register: _file_reboot_required

#- name: Restart Linux Machines if needed
#  shell: sleep 2 && shutdown -r now "Reboot triggered by ansible"
#  ignore_errors: True
#  when: _file_reboot_required.stat.exists
#  async: 1
#  poll: 0

#- name: Wait for Connection
#  wait_for_connection:
#    delay: 60
#  when: _file_reboot_required.stat.exists
