---

- name: Install 3 Base Apt-Utils and Update Cache
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  with_items:
    - aptitude
    - apt
    - apt-utils
  become: true

- name: Confirm Universally Required Apps Are Installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  with_items:
    - "{{ universal_apt }}"
  become: true

- name: Run Basic, Safe, Full and Dist Upgrade with apt Module
  apt: upgrade="{{ item }}"
  with_items:
    - yes
    - safe
    - full
    - dist
  register: _upgrade_apt
  failed_when: False
  become: true

#- debug: var=_upgrade_apt
#  when: _upgrade_apt|changed

- name: Autoremove Command in apt Module
  apt: autoremove=yes
  register: _autoclean_apt
  failed_when: False
  become: true

#- debug: var=_autoclean_apt
#  when: _autoclean_apt|changed
