---

- name: Install 3 Base Apt-Utils and Update Cache
  apt:
    name: "[ aptitude, apt, apt-utils ]"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  become: true

- name: Confirm Universally Required Apps Are Installed
  apt:
    name: "{{ universal_apt }}"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  become: true

- name: Run Basic, Safe, Full and Dist Upgrade with apt Module
  apt: upgrade="{{ item }}"
  with_items:
    - yes
    - safe
    - full
    - dist
  register: _upgrade_apt
  failed_when: False
  become: true

#- debug: var=_upgrade_apt
#  when: _upgrade_apt|changed

- name: Autoremove Command in apt Module
  apt: autoremove=yes
  register: _autoclean_apt
  failed_when: False
  become: true

#- debug: var=_autoclean_apt
#  when: _autoclean_apt|changed

- name: Check if Reboot is Needed
  stat:
    path: /var/run/reboot-required
  register: _file_reboot_required

- name: Restart Linux Machines if needed
  shell: sleep 2 && shutdown -r now "Reboot triggered by ansible"
  ignore_errors: True
  when: _file_reboot_required.stat.exists
  async: 1
  poll: 0

- name: Wait for Connection
  wait_for_connection:
    delay: 60
  when: _file_reboot_required.stat.exists
